// <auto-generated />
using System;
using Locked_IN_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Locked_IN_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230135601_FixChatSequences")]
    partial class FixChatSequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("chat_pk");

                    b.HasIndex("TeamId");

                    b.ToTable("chat");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chatparticipant", b =>
                {
                    b.Property<int>("ChatparticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chatparticipant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatparticipantId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_read_at");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("unread_count");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ChatparticipantId")
                        .HasName("chatparticipant_pk");

                    b.HasIndex("ChatId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("chatparticipant");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.ExperienceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Experiencelevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("experiencelevel");

                    b.HasKey("Id")
                        .HasName("experience_tag_pk");

                    b.ToTable("experience_tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Experiencelevel = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Experiencelevel = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Experiencelevel = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            Experiencelevel = "Professional"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_timestamp");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("User2Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_2_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("friendship_pk");

                    b.HasIndex("StatusId");

                    b.HasIndex("User2Id");

                    b.HasIndex("UserId");

                    b.ToTable("friendship");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RequestTimestamp = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 2,
                            User2Id = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RequestTimestamp = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 1,
                            User2Id = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.FriendshipStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("friendship_status_pk");

                    b.ToTable("friendship_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Blocked"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("game_pk");

                    b.ToTable("game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 2,
                            Name = "League of Legends"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Valorant"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameExp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("experience");

                    b.HasKey("Id")
                        .HasName("game_exp_pk");

                    b.ToTable("game_exp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Experience = "< 100 hours"
                        },
                        new
                        {
                            Id = 2,
                            Experience = "100-500 hours"
                        },
                        new
                        {
                            Id = 3,
                            Experience = "500-1000 hours"
                        },
                        new
                        {
                            Id = 4,
                            Experience = "1000+ hours"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceTagId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_tag_id");

                    b.Property<int>("GameExpId")
                        .HasColumnType("integer")
                        .HasColumnName("game_exp_id");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<bool>("Isfavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("isfavorite");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("game_profile_pk");

                    b.HasIndex("ExperienceTagId");

                    b.HasIndex("GameExpId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("game_profile");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameProfilePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("game_profile_id");

                    b.Property<int>("GameplayPrefId")
                        .HasColumnType("integer")
                        .HasColumnName("gameplay_pref_id");

                    b.HasKey("Id")
                        .HasName("game_profile_pref_pk");

                    b.HasIndex("GameProfileId");

                    b.HasIndex("GameplayPrefId");

                    b.ToTable("game_profile_pref");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameplayPref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preference");

                    b.HasKey("Id")
                        .HasName("gameplay_pref_pk");

                    b.ToTable("gameplay_pref");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Preference = "Voice Chat Only"
                        },
                        new
                        {
                            Id = 2,
                            Preference = "Ping Only"
                        },
                        new
                        {
                            Id = 3,
                            Preference = "Any Communication"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameprofilePreferencetagRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("game_profile_id");

                    b.Property<int>("PreferenceTagId")
                        .HasColumnType("integer")
                        .HasColumnName("preference_tag_id");

                    b.HasKey("Id")
                        .HasName("gameprofile_preferencetag_relation_pk");

                    b.HasIndex("GameProfileId");

                    b.HasIndex("PreferenceTagId");

                    b.ToTable("gameprofile_preferencetag_relation");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.MemberStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Statusname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statusname");

                    b.HasKey("Id")
                        .HasName("member_status_pk");

                    b.ToTable("member_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Statusname = "Leader"
                        },
                        new
                        {
                            Id = 2,
                            Statusname = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Statusname = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            Statusname = "Rejected"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attachment_url");

                    b.Property<int>("ChatparticipantChatparticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("chatparticipant_chatparticipant_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("message_pk");

                    b.HasIndex("ChatparticipantChatparticipantId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.PreferenceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Preferencename")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferencename");

                    b.HasKey("Id")
                        .HasName("preference_tag_pk");

                    b.ToTable("preference_tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Preferencename = "Competitive"
                        },
                        new
                        {
                            Id = 2,
                            Preferencename = "Casual"
                        },
                        new
                        {
                            Id = 3,
                            Preferencename = "Communication"
                        },
                        new
                        {
                            Id = 4,
                            Preferencename = "Strategy Focus"
                        },
                        new
                        {
                            Id = 5,
                            Preferencename = "Fun First"
                        },
                        new
                        {
                            Id = 6,
                            Preferencename = "Skill Development"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rolename");

                    b.HasKey("Id")
                        .HasName("role_pk");

                    b.ToTable("role");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_timespamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceTagId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_tag_id");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("Isblitz")
                        .HasColumnType("boolean")
                        .HasColumnName("isblitz");

                    b.Property<bool>("Isprivate")
                        .HasColumnType("boolean")
                        .HasColumnName("isprivate");

                    b.Property<int>("MaxPlayerCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_player_count");

                    b.Property<int?>("MinCompScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_comp_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("team_pk");

                    b.HasIndex("ExperienceTagId");

                    b.HasIndex("GameId");

                    b.ToTable("team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTimestamp = new DateTime(2024, 9, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TestDescription1",
                            ExperienceTagId = 3,
                            GameId = 1,
                            IconUrl = "https://pl.wikipedia.org/wiki/World_of_Warcraft#/media/Plik:WoW_icon.svg",
                            Isblitz = false,
                            Isprivate = false,
                            MaxPlayerCount = 5,
                            MinCompScore = 1500,
                            Name = "CS2 Legends"
                        },
                        new
                        {
                            Id = 2,
                            CreationTimestamp = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TestDescription2",
                            ExperienceTagId = 1,
                            GameId = 2,
                            IconUrl = "https://pl.wikipedia.org/wiki/World_of_Warcraft#/media/Plik:WoW_icon.svg",
                            Isblitz = true,
                            Isprivate = true,
                            MaxPlayerCount = 5,
                            MinCompScore = 800,
                            Name = "LoL Rookies"
                        },
                        new
                        {
                            Id = 3,
                            CreationTimestamp = new DateTime(2024, 10, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TestDescription3",
                            ExperienceTagId = 4,
                            GameId = 3,
                            IconUrl = "https://pl.wikipedia.org/wiki/World_of_Warcraft#/media/Plik:WoW_icon.svg",
                            Isblitz = false,
                            Isprivate = false,
                            MaxPlayerCount = 5,
                            MinCompScore = 2000,
                            Name = "Valorant Pros"
                        },
                        new
                        {
                            Id = 4,
                            CreationTimestamp = new DateTime(2024, 10, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TestDescription4",
                            ExperienceTagId = 2,
                            GameId = 2,
                            IconUrl = "https://pl.wikipedia.org/wiki/World_of_Warcraft#/media/Plik:WoW_icon.svg",
                            Isblitz = true,
                            Isprivate = false,
                            MaxPlayerCount = 6,
                            Name = "Casual Gamers"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Isleader")
                        .HasColumnType("boolean")
                        .HasColumnName("isleader");

                    b.Property<DateTime>("Jointimestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("jointimestamp");

                    b.Property<int>("MemberStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("member_status_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("team_member_pk");

                    b.HasIndex("MemberStatusId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("team_member");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Isleader = true,
                            Jointimestamp = new DateTime(2024, 9, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 1,
                            TeamId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Isleader = false,
                            Jointimestamp = new DateTime(2024, 10, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 2,
                            TeamId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Isleader = true,
                            Jointimestamp = new DateTime(2024, 10, 8, 16, 15, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 1,
                            TeamId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Isleader = false,
                            Jointimestamp = new DateTime(2024, 10, 13, 11, 45, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 3,
                            TeamId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Isleader = true,
                            Jointimestamp = new DateTime(2024, 10, 18, 9, 20, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 1,
                            TeamId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Isleader = true,
                            Jointimestamp = new DateTime(2024, 10, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            MemberStatusId = 1,
                            TeamId = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.TeamPreferencetagRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PreferenceTagId")
                        .HasColumnType("integer")
                        .HasColumnName("preference_tag_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("team_preferencetag_relation_pk");

                    b.HasIndex("PreferenceTagId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_preferencetag_relation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PreferenceTagId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            PreferenceTagId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            PreferenceTagId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            PreferenceTagId = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            PreferenceTagId = 1,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            PreferenceTagId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            PreferenceTagId = 2,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 8,
                            PreferenceTagId = 6,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("availability");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashed_pass");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = "{\"monday\": [\"18:00\", \"22:00\"], \"friday\": [\"19:00\", \"23:00\"]}",
                            AvatarUrl = "https://example.com/avatars/john.png",
                            Email = "john.doe@example.com",
                            HashedPass = "hashed_password_1",
                            Nickname = "JohnDoe"
                        },
                        new
                        {
                            Id = 2,
                            Availability = "{\"tuesday\": [\"17:00\", \"21:00\"], \"saturday\": [\"14:00\", \"18:00\"]}",
                            Email = "jane.smith@example.com",
                            HashedPass = "hashed_password_2",
                            Nickname = "JaneSmith"
                        },
                        new
                        {
                            Id = 3,
                            Availability = "{\"wednesday\": [\"20:00\", \"24:00\"], \"sunday\": [\"16:00\", \"20:00\"]}",
                            Email = "mike.wilson@example.com",
                            HashedPass = "hashed_password_3",
                            Nickname = "MikeWilson"
                        },
                        new
                        {
                            Id = 4,
                            Availability = "{\"thursday\": [\"19:00\", \"23:00\"], \"saturday\": [\"15:00\", \"19:00\"]}",
                            Email = "sarah.johnson@example.com",
                            HashedPass = "hashed_password_4",
                            Nickname = "SarahJ"
                        },
                        new
                        {
                            Id = 5,
                            Availability = "{}",
                            Email = "test.user5@example.com",
                            HashedPass = "hashed_password_5",
                            Nickname = "TestUser5"
                        },
                        new
                        {
                            Id = 6,
                            Availability = "{}",
                            Email = "test.user6@example.com",
                            HashedPass = "hashed_password_6",
                            Nickname = "TestUser6"
                        });
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chat", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.Team", "Team")
                        .WithMany("Chats")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chatparticipant", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.Chat", "Chat")
                        .WithMany("Chatparticipants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locked_IN_Backend.Data.Entities.Role", "Role")
                        .WithMany("Chatparticipants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locked_IN_Backend.Data.Entities.User", "User")
                        .WithMany("Chatparticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Friendship", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.FriendshipStatus", "Status")
                        .WithMany("Friendships")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("friendship_status");

                    b.HasOne("Locked_IN_Backend.Data.Entities.User", "User2")
                        .WithMany("FriendshipUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("friendship_user_2");

                    b.HasOne("Locked_IN_Backend.Data.Entities.User", "User")
                        .WithMany("FriendshipUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("friendship_user_1");

                    b.Navigation("Status");

                    b.Navigation("User");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameProfile", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.ExperienceTag", "ExperienceTag")
                        .WithMany("GameProfiles")
                        .HasForeignKey("ExperienceTagId")
                        .IsRequired()
                        .HasConstraintName("game_profile_experience_tag");

                    b.HasOne("Locked_IN_Backend.Data.Entities.GameExp", "GameExp")
                        .WithMany("GameProfiles")
                        .HasForeignKey("GameExpId")
                        .IsRequired()
                        .HasConstraintName("game_profile_game_exp");

                    b.HasOne("Locked_IN_Backend.Data.Entities.Game", "Game")
                        .WithMany("GameProfiles")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("user_game_game");

                    b.HasOne("Locked_IN_Backend.Data.Entities.User", "User")
                        .WithMany("GameProfiles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_game_user");

                    b.Navigation("ExperienceTag");

                    b.Navigation("Game");

                    b.Navigation("GameExp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameProfilePref", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.GameProfile", "GameProfile")
                        .WithMany("GameProfilePrefs")
                        .HasForeignKey("GameProfileId")
                        .IsRequired()
                        .HasConstraintName("game_profile_pref_game_profile");

                    b.HasOne("Locked_IN_Backend.Data.Entities.GameplayPref", "GameplayPref")
                        .WithMany("GameProfilePrefs")
                        .HasForeignKey("GameplayPrefId")
                        .IsRequired()
                        .HasConstraintName("game_profile_pref_gameplay_pref");

                    b.Navigation("GameProfile");

                    b.Navigation("GameplayPref");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameprofilePreferencetagRelation", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.GameProfile", "GameProfile")
                        .WithMany("GameprofilePreferencetagRelations")
                        .HasForeignKey("GameProfileId")
                        .IsRequired()
                        .HasConstraintName("gameprofile_preferencetag_relation_game_profile");

                    b.HasOne("Locked_IN_Backend.Data.Entities.PreferenceTag", "PreferenceTag")
                        .WithMany("GameprofilePreferencetagRelations")
                        .HasForeignKey("PreferenceTagId")
                        .IsRequired()
                        .HasConstraintName("gameprofile_preferencetag_relation_preference_tag");

                    b.Navigation("GameProfile");

                    b.Navigation("PreferenceTag");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Message", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.Chatparticipant", "ChatparticipantChatparticipant")
                        .WithMany("Messages")
                        .HasForeignKey("ChatparticipantChatparticipantId")
                        .IsRequired()
                        .HasConstraintName("message_chatparticipant");

                    b.Navigation("ChatparticipantChatparticipant");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Team", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.ExperienceTag", "ExperienceTag")
                        .WithMany("Teams")
                        .HasForeignKey("ExperienceTagId")
                        .IsRequired()
                        .HasConstraintName("team_experience_tag");

                    b.HasOne("Locked_IN_Backend.Data.Entities.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("team_game");

                    b.Navigation("ExperienceTag");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.TeamMember", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.MemberStatus", "MemberStatus")
                        .WithMany("TeamMembers")
                        .HasForeignKey("MemberStatusId")
                        .IsRequired()
                        .HasConstraintName("team_member_status");

                    b.HasOne("Locked_IN_Backend.Data.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("team_member_team");

                    b.HasOne("Locked_IN_Backend.Data.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("team_member_user");

                    b.Navigation("MemberStatus");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.TeamPreferencetagRelation", b =>
                {
                    b.HasOne("Locked_IN_Backend.Data.Entities.PreferenceTag", "PreferenceTag")
                        .WithMany("TeamPreferencetagRelations")
                        .HasForeignKey("PreferenceTagId")
                        .IsRequired()
                        .HasConstraintName("team_preferencetag_relation_preference_tag");

                    b.HasOne("Locked_IN_Backend.Data.Entities.Team", "Team")
                        .WithMany("TeamPreferencetagRelations")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("team_preferencetag_relation_team");

                    b.Navigation("PreferenceTag");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chat", b =>
                {
                    b.Navigation("Chatparticipants");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Chatparticipant", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.ExperienceTag", b =>
                {
                    b.Navigation("GameProfiles");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.FriendshipStatus", b =>
                {
                    b.Navigation("Friendships");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Game", b =>
                {
                    b.Navigation("GameProfiles");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameExp", b =>
                {
                    b.Navigation("GameProfiles");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameProfile", b =>
                {
                    b.Navigation("GameProfilePrefs");

                    b.Navigation("GameprofilePreferencetagRelations");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.GameplayPref", b =>
                {
                    b.Navigation("GameProfilePrefs");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.MemberStatus", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.PreferenceTag", b =>
                {
                    b.Navigation("GameprofilePreferencetagRelations");

                    b.Navigation("TeamPreferencetagRelations");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Role", b =>
                {
                    b.Navigation("Chatparticipants");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.Team", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("TeamMembers");

                    b.Navigation("TeamPreferencetagRelations");
                });

            modelBuilder.Entity("Locked_IN_Backend.Data.Entities.User", b =>
                {
                    b.Navigation("Chatparticipants");

                    b.Navigation("FriendshipUser2s");

                    b.Navigation("FriendshipUsers");

                    b.Navigation("GameProfiles");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
